# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20161021_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_item',
        ),
        migrations.AddField(
            model_name='order',
            name='food_item',
            field=models.ManyToManyField(to='pos.FoodItem'),
        ),
    ]
